### PR TITLE
fixed image locations in summit labs

### PR DESCRIPTION
**Pull request by hodrigohamalho**

### CODE REVIEW

**Review by ppatierno — COMMENTED** [review]
We already have this attribute in the root doc file:
:imagesdir: ./images
Did you have any problems with that?

**Comment by hodrigohamalho** [comment]
Yes, I did. The images doesn't load.

**Comment by ppatierno** [comment]
I know that images aren't showed in the GitHub repo but the documentation is made with the objective to be made using asciidoctor in order to build the final HTML file and not having them available directly in the repo.

**Comment by ppatierno** [comment]
Another thing, I don't think that we have to adapt the documentation to the new Strimzi version. This is the demo of the RH Summit 2018 where we used Strimzi 0.3.0 during the lab. We don't want to update this demo every time a new Strimzi version will come.

**Comment by hodrigohamalho** [comment]
I agree with you with the demo update strategy, but the documentation (broken images, etc) I think it should be always working independent of the version.

Just my 2cents.

**Comment by ppatierno** [comment]
I see your point but Strimzi is a fast evolving project and breaking changes happen quite easily. For this reason the summit 2018 demo should work out of box without changes. We'll hve something different in the future as you suggest with doc not related to release.

**Pull request closed without merging**
